//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        public Change()
        {
            this.ChangeAudit = new HashSet<ChangeAudit>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public System.DateTime RegsterTime { get; set; }
        public int AuditStatus { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual ICollection<ChangeAudit> ChangeAudit { get; set; }
    }
}
