//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compact
    {
        public int Id { get; set; }
        public Nullable<decimal> OfficialSalary { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> IsBuyInsurance { get; set; }
        public Nullable<System.DateTime> SignTime { get; set; }
        public string SignType { get; set; }
        public string CompactStatus { get; set; }
        public string File { get; set; }
        public string RegsterPerson { get; set; }
        public Nullable<System.DateTime> RegsterTime { get; set; }
        public string Content { get; set; }
    
        public virtual CompactType CompactType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
