//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonnelEntities : DbContext
    {
        public PersonnelEntities()
            : base("name=PersonnelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASLevel> ASLevel { get; set; }
        public DbSet<Bulletin> Bulletin { get; set; }
        public DbSet<Button> Button { get; set; }
        public DbSet<Change> Change { get; set; }
        public DbSet<ChangeAudit> ChangeAudit { get; set; }
        public DbSet<Compact> Compact { get; set; }
        public DbSet<CompactType> CompactType { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<Dimission> Dimission { get; set; }
        public DbSet<EducationExperience> EducationExperience { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Evection> Evection { get; set; }
        public DbSet<Inform> Inform { get; set; }
        public DbSet<Leave> Leave { get; set; }
        public DbSet<LeaveType> LeaveType { get; set; }
        public DbSet<LoginLog> LoginLog { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<MenuButton> MenuButton { get; set; }
        public DbSet<RewarAndPunish> RewarAndPunish { get; set; }
        public DbSet<RewarAndPunishAudit> RewarAndPunishAudit { get; set; }
        public DbSet<RewarAndPunishProject> RewarAndPunishProject { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<RoleMenuButton> RoleMenuButton { get; set; }
        public DbSet<TrainCourse> TrainCourse { get; set; }
        public DbSet<TrainExperience> TrainExperience { get; set; }
        public DbSet<TrainPerson> TrainPerson { get; set; }
        public DbSet<TrainPlan> TrainPlan { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserOperateLog> UserOperateLog { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<WorkExperience> WorkExperience { get; set; }
        public DbSet<SignIn> SignIn { get; set; }
    }
}
