//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Bulletin = new HashSet<Bulletin>();
            this.Change = new HashSet<Change>();
            this.Change1 = new HashSet<Change>();
            this.Employee = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> AuditMaxLeaveDays { get; set; }
        public Nullable<decimal> AuditMaxMoney { get; set; }
        public Nullable<int> MainPrincipal { get; set; }
        public Nullable<int> SubordinationPrincipal { get; set; }
        public int Sort { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual ICollection<Bulletin> Bulletin { get; set; }
        public virtual ICollection<Change> Change { get; set; }
        public virtual ICollection<Change> Change1 { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
