//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationExperience
    {
        public int Id { get; set; }
        public string GraduateSchool { get; set; }
        public string StudyMajor { get; set; }
        public Nullable<int> XueLi { get; set; }
        public Nullable<bool> IfObtainedCertificate { get; set; }
        public string ImgSrc { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> IfGraduate { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
