//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Bulletin = new HashSet<Bulletin>();
            this.Change = new HashSet<Change>();
            this.Change1 = new HashSet<Change>();
            this.Change2 = new HashSet<Change>();
            this.ChangeAudit = new HashSet<ChangeAudit>();
            this.Compact = new HashSet<Compact>();
            this.Dimission = new HashSet<Dimission>();
            this.Dimission1 = new HashSet<Dimission>();
            this.EducationExperience = new HashSet<EducationExperience>();
            this.Evection = new HashSet<Evection>();
            this.Evection1 = new HashSet<Evection>();
            this.Evection2 = new HashSet<Evection>();
            this.Inform = new HashSet<Inform>();
            this.Leave = new HashSet<Leave>();
            this.Leave1 = new HashSet<Leave>();
            this.Leave2 = new HashSet<Leave>();
            this.RewarAndPunish = new HashSet<RewarAndPunish>();
            this.RewarAndPunishAudit = new HashSet<RewarAndPunishAudit>();
            this.RewarAndPunish1 = new HashSet<RewarAndPunish>();
            this.RewarAndPunish2 = new HashSet<RewarAndPunish>();
            this.TrainExperience = new HashSet<TrainExperience>();
            this.TrainPerson = new HashSet<TrainPerson>();
            this.User = new HashSet<User>();
            this.WorkExperience = new HashSet<WorkExperience>();
        }
    
        public int Id { get; set; }
        public string Work { get; set; }
        public string Name { get; set; }
        public string OldName { get; set; }
        public string EnglishName { get; set; }
        public string Sex { get; set; }
        public string PoliticsStatus { get; set; }
        public string Nation { get; set; }
        public string Marriage { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public decimal BaseSalary { get; set; }
        public string PictureSrc { get; set; }
        public string BankAccount { get; set; }
        public string GraduateSchool { get; set; }
        public string StudyMajor { get; set; }
        public Nullable<int> XueLi { get; set; }
        public string IdentityCard { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Anmelden { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string NativePlace { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string CurAddress { get; set; }
        public string HealthState { get; set; }
        public string HousingCase { get; set; }
        public string Hobby { get; set; }
        public string Speciality { get; set; }
        public bool EmployeeStatus { get; set; }
        public string Description { get; set; }
    
        public virtual ASLevel ASLevel { get; set; }
        public virtual ICollection<Bulletin> Bulletin { get; set; }
        public virtual ICollection<Change> Change { get; set; }
        public virtual ICollection<Change> Change1 { get; set; }
        public virtual ICollection<Change> Change2 { get; set; }
        public virtual ICollection<ChangeAudit> ChangeAudit { get; set; }
        public virtual ICollection<Compact> Compact { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Dimission> Dimission { get; set; }
        public virtual ICollection<Dimission> Dimission1 { get; set; }
        public virtual ICollection<EducationExperience> EducationExperience { get; set; }
        public virtual ICollection<Evection> Evection { get; set; }
        public virtual ICollection<Evection> Evection1 { get; set; }
        public virtual ICollection<Evection> Evection2 { get; set; }
        public virtual ICollection<Inform> Inform { get; set; }
        public virtual ICollection<Leave> Leave { get; set; }
        public virtual ICollection<Leave> Leave1 { get; set; }
        public virtual ICollection<Leave> Leave2 { get; set; }
        public virtual ICollection<RewarAndPunish> RewarAndPunish { get; set; }
        public virtual ICollection<RewarAndPunishAudit> RewarAndPunishAudit { get; set; }
        public virtual ICollection<RewarAndPunish> RewarAndPunish1 { get; set; }
        public virtual ICollection<RewarAndPunish> RewarAndPunish2 { get; set; }
        public virtual ICollection<TrainExperience> TrainExperience { get; set; }
        public virtual ICollection<TrainPerson> TrainPerson { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<WorkExperience> WorkExperience { get; set; }
    }
}
