//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public LeaveType()
        {
            this.Leave = new HashSet<Leave>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LeaveDays { get; set; }
        public Nullable<decimal> OneDayMoney { get; set; }
        public Nullable<decimal> DeductMoney { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Leave> Leave { get; set; }
    }
}
