//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuButton = new HashSet<MenuButton>();
            this.RoleMenuButton = new HashSet<RoleMenuButton>();
        }
    
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string LinkAddress { get; set; }
        public string Icon { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public int Sort { get; set; }
    
        public virtual ICollection<MenuButton> MenuButton { get; set; }
        public virtual ICollection<RoleMenuButton> RoleMenuButton { get; set; }
    }
}
