//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewarAndPunish
    {
        public RewarAndPunish()
        {
            this.RewarAndPunishAudit = new HashSet<RewarAndPunishAudit>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> RTime { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<bool> RewarOrPunish { get; set; }
        public System.DateTime RegsterTime { get; set; }
        public int AuditStatus { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual RewarAndPunishProject RewarAndPunishProject { get; set; }
        public virtual ICollection<RewarAndPunishAudit> RewarAndPunishAudit { get; set; }
    }
}
