//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainPerson
    {
        public TrainPerson()
        {
            this.SignIn = new HashSet<SignIn>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> IsAccept { get; set; }
        public Nullable<int> TrainNumber { get; set; }
        public Nullable<int> TotalPoints { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual TrainPlan TrainPlan { get; set; }
        public virtual ICollection<SignIn> SignIn { get; set; }
    }
}
