//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainPlan
    {
        public TrainPlan()
        {
            this.TrainPerson = new HashSet<TrainPerson>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> TrainDays { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string TrainLecturer { get; set; }
        public Nullable<System.DateTime> PlanTime { get; set; }
        public string PlanPerson { get; set; }
        public string Description { get; set; }
    
        public virtual TrainCourse TrainCourse { get; set; }
        public virtual ICollection<TrainPerson> TrainPerson { get; set; }
    }
}
