//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserOperateLog = new HashSet<UserOperateLog>();
            this.UserRole = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public bool IsAble { get; set; }
        public bool IfChangePwd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<UserOperateLog> UserOperateLog { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
